# Generated by Django 5.0.6 on 2024-08-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_emergency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='player_id',
        ),
    ]
