# Generated by Django 5.0.6 on 2024-08-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_contact_emergency_user_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/')),
                ('survey_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
