# Generated by Django 5.0.6 on 2024-08-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='logo',
        ),
    ]
