# Generated by Django 5.0.6 on 2024-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_post_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video',
            new_name='media',
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
