# Generated by Django 5.0.6 on 2024-08-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivity',
            options={'verbose_name_plural': 'UserActivities'},
        ),
    ]
